
version: '3.7'

# Define services/containers
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: bob123!
      MYSQL_DATABASE: key_db
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob123!
    ports:
      - 3307:3306
    volumes:
      - ./database-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  app:
    build: .
    ports:
      - 555:888
    environment:
      DATABASE_URL: mysql://root:bob123!@db:3306/key_db?schema=public
    depends_on:
      - db
    links:
      - db

